## Numpy

In [2]:
import numpy as np

### Basic exercises 

####  Ceate a 1D array of numbers from 0 to 9

In [3]:
# Solution
[...]


[Ellipsis]

#### Create a 3×3 numpy array of all True’s

In [4]:
# Solution
[...]

[Ellipsis]

#### Replace all odd numbers in arr with -1

In [5]:
# Input
arr = np.arange(10)

# Solution
[...]

[Ellipsis]

#### Convert a 1D array to a 2D array with 2 rows

In [6]:
# Input
arr = np.arange(10)
print(arr)

# Solution
[...]

[0 1 2 3 4 5 6 7 8 9]


[Ellipsis]

#### Stack arrays a and b vertically and then horizontally

In [7]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# Solution
[...]

[Ellipsis]

#### Find positions where elements of a and b match

In [8]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
[...]

[Ellipsis]

####  Get all items between 5 and 10 from a

In [9]:
# Input
a = np.arange(15)

# Solutions
[...]

[Ellipsis]

#### Get the positions of top 5 maximum values in a given array a

In [10]:
# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Solution:
[...]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]


[Ellipsis]

#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))

In [11]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution
[...]

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


[Ellipsis]

####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [12]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
[...]

Array:  [0 0 3 0 2 4 2 2 2 2]


[Ellipsis]

#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [13]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
# Soluzione
[...]

[Ellipsis]

#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [14]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Solution
[...]

[Ellipsis]

### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [16]:
# Input filepath
FILEPATH = [...]
# Soultion
[...]

[Ellipsis]

#### Print the unique labels of the dataset

In [17]:
# Solution
[...]

[Ellipsis]

#### Find how many samples (i.e. rows) we have for each unique label

In [18]:
# Solution
[...]

[Ellipsis]

#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [19]:
# Solution
[...]

[Ellipsis]

####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [20]:
# Solution
[...]

[Ellipsis]

####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [21]:
# Solution
[...]

[Ellipsis]

#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)

In [22]:
[...]

[Ellipsis]

#### Sort the iris dataset based on sepallength column

In [23]:
# Solution
[...]

[Ellipsis]

#### Find the most frequent value of petal length (3rd column) in iris dataset

In [24]:
# Solution
[...]

[Ellipsis]

#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)

In [25]:
# Solution
[...]

[Ellipsis]

#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [26]:
# Solution
[...]

[Ellipsis]