## Numpy


In [1]:
import numpy as np

### Basic exercises


#### Ceate a 1D array of numbers from 0 to 9


In [2]:
# Solution
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 3×3 numpy array of all True’s


In [3]:
# Solution
true_matrix = np.full((3, 3), True)

#### Replace all odd numbers in arr with -1


In [6]:
# Input
arr = np.arange(10)

# Solution
arr[arr % 2 == 1] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Convert a 1D array to a 2D array with 2 rows


In [7]:
# Input
arr = np.arange(10)
print(arr)

# Solution
arr = arr.reshape(2, -1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Stack arrays a and b vertically and then horizontally


In [8]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# Solution
vertical_stack = np.vstack([a, b])
horizontal_stack = np.hstack([a, b])
print(vertical_stack)
print(horizontal_stack)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Find positions where elements of a and b match


In [9]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
match = np.where(a == b)
print(match)

(array([1, 3, 5, 7]),)


#### Get all items between 5 and 10 from a


In [10]:
# Input
a = np.arange(15)

# Solutions
print(a[(a >= 5) & (a <= 10)])

[ 5  6  7  8  9 10]


#### Get the positions of top 5 maximum values in a given array a


In [17]:
# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Solution:
print(np.sort(a)[::-1][0:5])

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[48.95256545 44.67477576 42.39403048 41.466785   40.99501269]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))


In [20]:
# Input
np.random.seed(100)
a = np.random.randint(1, 10, [5, 3])
print(a)

# Solution
print(np.apply_along_axis(lambda x: np.min(x) / np.max(x), arr=a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0.44444444 0.125      0.5        1.         0.11111111]


#### Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.


In [44]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)

# Solution
# what??

b = np.full_like(a, False)
unique_indices, counts = np.unique(a, return_counts=True)
print(unique_indices, counts)

for e in unique_indices[counts >= 2]:
    b[np.where(a == e)] = True

print(b)

[0 0 3 0 2 4 2 2 2 2]
[0 2 3 4] [3 5 1 1]
[1 1 0 1 1 0 1 1 1 1]


#### Find the index of 5th repetition of number 1 in x

Make use of numpy.where


In [50]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
# Soluzione
print(np.where(x == 1)[0][n - 1])

8


#### Compute the moving average of window size 3, for the given 1D array

Make use of numpy.convolve


In [55]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Solution

moving_avg = np.convolve(arr, np.ones(3) / 3)
# print(moving_avg) # deve ignorare primi ultimi due
print(moving_avg[2:-2])

[6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset


#### Import the iris dataset from iris.txt

See np.genfromtxt, load the dataset with dtype=np.str


In [15]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive


In [27]:
# Input filepath
FILEPATH = "basics-data/iris.txt"
# Soultion
data = np.genfromtxt(FILEPATH, delimiter=",", usecols=[0, 1, 2, 3])
labels = np.genfromtxt(FILEPATH, delimiter=",", usecols=[4], dtype="str")
print(data[:3])
print(labels[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa']


#### Print the unique labels of the dataset


In [15]:
# Solution
unique_labels, c = np.unique(labels, return_counts=True)
print(unique_labels)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label


In [16]:
# Solution
print(unique_labels, c)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica'] [50 50 50]


#### Find the mean, median, standard deviation of iris's sepallength (1st column)

See np.genfromtxt, load only the 1st column with the appropiate data type


In [17]:
# Solution
sepal_length=np.genfromtxt(FILEPATH, delimiter=",", usecols=[0])
print(np.mean(sepal_length), np.median(sepal_length), np.std(sepal_length))

5.843333333333334 5.8 0.8253012917851409


#### Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels


In [18]:
# Solution
for label in np.unique(labels):
    sepal_length = data[labels == label, 0]
    print(label, np.mean(sepal_length), np.median(sepal_length), np.std(sepal_length))


Iris-setosa 5.006 5.0 0.3489469873777391
Iris-versicolor 5.936 5.9 0.5109833656783751
Iris-virginica 6.587999999999998 6.5 0.6294886813914926


#### Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3


In [31]:
# Solution
# add a column of volume

newdata = np.genfromtxt(FILEPATH, delimiter=",", usecols=[0, 1, 2, 3])
newdata = np.insert(data, 4, (np.pi * data[:, 2] * data[:, 3] * data[:, 3]) / 3, axis=1)

print(newdata[:3])

[[5.1        3.5        1.4        0.2        0.05864306]
 [4.9        3.         1.4        0.2        0.05864306]
 [4.7        3.2        1.3        0.2        0.05445427]]


#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica

See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)


In [49]:
#Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
# Solution
np.random.seed(100)

species = np.genfromtxt(FILEPATH, delimiter=",", usecols=[4], dtype="str")
unique=np.unique(species)
weights = [2, 1, 1]

print(np.random.choice(species, 20, weights))


['Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica']


#### Sort the iris dataset based on sepallength column


In [50]:
# Solution
sorted_data_sepal_length = data[data[:, 0].argsort()[::-1]]
print(sorted_data_sepal_length[:3])

[[7.9 3.8 6.4 2. ]
 [7.7 3.  6.1 2.3]
 [7.7 3.8 6.7 2.2]]


#### Find the most frequent value of petal length (3rd column) in iris dataset


In [58]:
# Solution
pl=np.genfromtxt(FILEPATH, delimiter=",", usecols=[2])
val,count=np.unique(pl,return_counts=True)
print(val[np.argmax(count)],count[np.argmax(count)])

1.5 14


#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)


In [59]:
# Solution
pw=np.genfromtxt(FILEPATH, delimiter=",", usecols=[3])
print(np.argwhere(pw > 1.0)[0])

[50]


#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


In [71]:
# Solution
d=np.genfromtxt(FILEPATH, delimiter=",", usecols=[0,1,2,3])

print(np.argwhere((d[:,0]>5.0) & (d[:,3]<1.0)))

# print(d[(d[:,0]<5) & (d[:,2]>1.5)])

[[ 0]
 [ 5]
 [10]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [23]
 [27]
 [28]
 [31]
 [32]
 [33]
 [36]
 [39]
 [44]
 [46]
 [48]]
